from django.core.management.base import BaseCommand
import os
from datetime import datetime

class Command(BaseCommand):
    help = 'Generate a README.md file for the project'

    def handle(self, *args, **options):
        current_year = datetime.now().year
        
        readme = [
            '# Tourist Destination Manager',
            '',
            'A Django-based web application for managing tourist destinations.',
            '',
            '## Features',
            '',
            '- **Destination Management**: Create, read, update, and delete tourist destinations',
            '- **Image Galleries**: Upload multiple images for each destination',
            '- **Responsive Design**: Works on desktop and mobile devices',
            '- **Admin Interface**: Easy-to-use admin panel for content management',
            '- **REST API**: Full-featured API for programmatic access',
            '',
            '## Requirements',
            '',
            '- Python 3.8+',
            '- Django 4.2+',
            '- PostgreSQL (recommended) or SQLite',
            '- Pillow (for image processing)',
            '',
            '## Installation',
            '',
            '1. Clone the repository:',
            '   ```bash',
            '   git clone https://github.com/yourusername/tourist-destination-manager.git',
            '   cd tourist-destination-manager',
            '   ```',
            '',
            '2. Create and activate a virtual environment:',
            '   ```bash',
            '   python -m venv venv',
            '   source venv/bin/activate  # On Windows: .\\venv\\Scripts\\activate',
            '   ```',
            '',
            '3. Install dependencies:',
            '   ```bash',
            '   pip install -r requirements.txt',
            '   ```',
            '',
            '4. Create a [.env](cci:7://file:///c:/Users/ASUS/OneDrive/Desktop/CascadeProjects/windsurf-project/.env:0:0-0:0) file with your settings:',
            '   ```ini',
            '   DEBUG=True',
            '   SECRET_KEY=your-secret-key-here',
            '   DB_NAME=your_db_name',
            '   DB_USER=your_db_user',
            '   DB_PASSWORD=your_db_password',
            '   DB_HOST=localhost',
            '   DB_PORT=5432',
            '   ```',
            '',
            '5. Run migrations:',
            '   ```bash',
            '   python manage.py migrate',
            '   ```',
            '',
            '6. Create a superuser:',
            '   ```bash',
            '   python manage.py createsuperuser',
            '   ```',
            '',
            '7. Run the development server:',
            '   ```bash',
            '   python manage.py runserver',
            '   ```',
            '',
            '8. Open your browser and go to http://localhost:8000',
            '',
            '## Project Structure',
            '',
            '```',
            'tourist-destination-manager/',
            '├── destinations/          # Main app for tourist destinations',
            '│   ├── migrations/       # Database migrations',
            '│   ├── static/           # Static files (CSS, JS, images)',
            '│   ├── templates/        # HTML templates',
            '│   ├── admin.py         # Admin configuration',
            '│   ├── apps.py          # App config',
            '│   ├── forms.py         # Forms for the app',
            '│   ├── models.py        # Database models',
            '│   ├── urls.py          # App URLs',
            '│   └── views.py         # View functions',
            '├── TouristDestinationManager/  # Project settings',
            '│   ├── settings.py      # Main settings file',
            '│   ├── urls.py          # Main URL configuration',
            '│   └── wsgi.py          # WSGI configuration',
            '├── .env                 # Environment variables',
            '├── manage.py            # Django management script',
            '└── requirements.txt     # Python dependencies',
            '```',
            '',
            '## API Documentation',
            '',
            'The API documentation is available at `/api/docs/` when running the development server.',
            '',
            '## Contributing',
            '',
            '1. Fork the repository',
            '2. Create your feature branch (`git checkout -b feature/AmazingFeature`)',
            '3. Commit your changes (`git commit -m \'Add some AmazingFeature\'`)',
            '4. Push to the branch (`git push origin feature/AmazingFeature`)',
            '5. Open a Pull Request',
            '',
            '## License',
            '',
            'This project is licensed under the MIT License - see the [LICENSE](LICENSE) file for details.',
            '',
            f'© {current_year} Tourist Destination Manager'
        ]
        
        # Write to file
        with open('README.md', 'w', encoding='utf-8') as f:
            f.write('\n'.join(readme))
        
        self.stdout.write(self.style.SUCCESS('README.md file generated'))